repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        args: []
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
#  - repo: https://github.com/PyCQA/isort
#    rev: 5.13.2
#    hooks:
#      - id: isort
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.10.0
#    hooks:
#      - id: mypy
#        additional_dependencies: ["types-redis"]
#  - repo: https://github.com/PyCQA/bandit
#    rev: 1.7.9
#    hooks:
#      - id: bandit
#        args: ["-c", "bandit.yaml", "-r", "src"]
